[project]
name = "szz-llm-project"
version = "0.1.0"
description = ""
authors = [
    {name = "Emanuele",email = "e.mandato@studenti.unisannio.it"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.poetry]
packages = [{include = "szz_llm_project", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = ">=3.10" # Versione minima di Python richiesta
PyDriller = "^2.6"  # Per l'analisi della cronologia Git
requests = "^2.31"   # Per comunicare con Qwen (Ollama)
pydantic = "^2.0"    # Per la validazione dei dati

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"      # Per la fase di Testing del corso [cite: 75]
pytest-cov = "^4.1"  # Per la White Box Testing (Coverage)

[project.scripts]
szz-run = "szz_llm_project.main:main"